<BaseButton@Button>:
    background_normal: ''
    background_color: 0, 0, 0, 0  
    size_hint: None, None
    size: 250, 50
    canvas.before:
        Color:
            rgba: (0.18, 0.18, 0.18, 1) if self.state == 'normal' else (0.26, 0.26, 0.26, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<MenuButton@BaseButton>:
    canvas.before:
        Color:
            rgba: (0.11, 0.11, 0.13, 1) if self.state == 'normal' else (0.21, 0.21, 0.26, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<BackButton@BaseButton>:
    size: 150, 50
    canvas.before:
        Color:
            rgba: (0.18, 0.18, 0.18, 1) if self.state == 'normal' else (0.29, 0.29, 0.29, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<ExitButton@BaseButton>:
    canvas.before:
        Color:
            rgba: (0.11, 0.11, 0.13, 1) if self.state == 'normal' else (0.83, 0.18, 0.18, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<MenuScreen>:
    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        BoxLayout:
            orientation: 'vertical'
            spacing: 15
            size_hint: None, None
            size: self.minimum_size

            Label:
                text: 'Калькулятор епта'

            MenuButton:
                text: 'К расчетам'
                on_release: 
                    app.root.transition.direction = 'left'
                    app.root.current = 'calc'

            MenuButton:
                text: 'Оптимизация'
                on_release: 
                    app.root.transition.direction = 'left'
                    app.root.current = 'optimize'

            ExitButton:
                text: 'Выход'
                on_release: app.stop()

<CalcScreen>:
    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 20

        Label:
            text: 'Расчет расстояния от антенны до спутника'
            font_size: 24
            size_hint_y: None
            height: 50
            halign: 'center'
            valign: 'middle'
            text_size: self.size
        Label:
            id: result_label
            text: ''
            size_hint_y: None
            height: 30
            color: 1, 1, 1, 1


        GridLayout:
            cols: 2
            row_default_height: 40
            row_force_default: True
            col_default_width: 250
            col_force_default: True
            spacing: 10

            Label:
                text: 'Координаты антенны:'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
            TextInput:
                id: ant_input
                hint_text: 'x; y; z'
                multiline: False


            Label:
                text: 'Координаты спутника:'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
            TextInput:
                id: sat_input
                hint_text: 'x; y; z'
                multiline: False


        BaseButton:
            text: 'Рассчитать'
            size_hint: None, None
            size: 250, 50
            pos_hint: {'center_x': 0.5}
            on_release:
                root.calculate()

        BackButton:
            text: 'Назад в меню'
            pos_hint: {'center_x': 0.5}
            on_release:
                app.root.transition.direction = 'right'
                app.root.current = 'menu'
