<BaseButton@Button>:
    background_normal: ''
    background_color: 0, 0, 0, 0  
    size_hint: None, None
    size: 250, 50
    canvas.before:
        Color:
            rgba: (0.18, 0.18, 0.18, 1) if self.state == 'normal' else (0.26, 0.26, 0.26, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<MenuButton@BaseButton>:
    canvas.before:
        Color:
            rgba: (0.11, 0.11, 0.13, 1) if self.state == 'normal' else (0.21, 0.21, 0.26, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<BackButton@BaseButton>:
    size: 150, 50
    canvas.before:
        Color:
            rgba: (0.18, 0.18, 0.18, 1) if self.state == 'normal' else (0.29, 0.29, 0.29, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<ExitButton@BaseButton>:
    canvas.before:
        Color:
            rgba: (0.11, 0.11, 0.13, 1) if self.state == 'normal' else (0.83, 0.18, 0.18, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<MenuScreen>:
    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        BoxLayout:
            orientation: 'vertical'
            spacing: 15
            size_hint: None, None
            size: self.minimum_size

            Label:
                text: 'Система анализа канала связи'
                font_size: '28sp'
                size_hint_y: None
                height: 60
                halign: 'center'
                valign: 'middle'
                text_size: self.size
                bold: True
                color: 1, 1, 1, 1

            BoxLayout:
                size_hint_y: 5

            MenuButton:
                text: 'К расчетам'
                on_release: 
                    app.root.transition.direction = 'left'
                    app.root.current = 'calc'

            MenuButton:
                text: 'Поиск той самой'
                on_release: 
                    app.root.transition.direction = 'left'
                    app.root.current = 'optimize'

            MenuButton:
                text: "Добавить или изменить антенну"
                on_release: 
                    app.root.transition.direction = 'left'
                    app.root.current = 'antedit'

            MenuButton:
                text: "Добавить или изменить спутник"
                on_release: 
                    app.root.transition.direction = 'left'
                    app.root.current = 'satedit'

            ExitButton:
                text: 'Сохранить и выйти'
                on_release: root.save_and_exit()
            Label:
                id: debug
                text: ''

<CalcScreen>:

    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 25

        Label:
            text: 'Расчет отношения сигнал/шум'
            font_size: '28sp'
            size_hint_y: None
            height: 60
            halign: 'center'
            valign: 'middle'
            text_size: self.size
            bold: True
            color: 1, 1, 1, 1

        Label:
            id: result_label
            text: ''
            size_hint_y: None
            height: 40
            color: 1, 0.8, 0, 1
            halign: 'center'
            valign: 'middle'
            text_size: self.size
            italic: True

        GridLayout:
            cols: 2
            spacing: 20
            BoxLayout:
                orientation: 'vertical'
                padding: 15
                spacing: 15
                canvas.before:
                    Color:
                        rgba: 0.15, 0.15, 0.15, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]

                Spinner:
                    id: antenna_spinner
                    text: 'Выберите антенну'
                    values: app.antennas_names_with_add
                    size_hint_y: None
                    size: 280, 50
                    background_color: 0.12, 0.12, 0.12, 1
                    color: 1, 1, 1, 1

                BaseButton:
                    pos_hint: {'center_x': 0.5}
                    text: 'Задать параметры антенны'
                    size_hint_y:  None
                    size: 280, 50
                    on_release: 
                        app.root.transition.direction = 'up'
                        app.root.current = 'tempant'

                Label:
                    text: 'Координаты антенны:'
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size
                    size_hint_y: None
                    height: 30
                    color: 1, 1, 1, 1
                    bold: True

                TextInput:
                    id: ant_cords_input
                    hint_text: 'широта; долгота; высота над у.м.'
                    multiline: False
                    size_hint_y: None
                    size: 280, 50
                    background_color: 0.1, 0.1, 0.1, 1
                    foreground_color: 1, 1, 1, 1
                    padding: [10, 10, 10, 10]
                    font_size: 16

            BoxLayout:
                orientation: 'vertical'
                padding: 15
                spacing: 15
                canvas.before:
                    Color:
                        rgba: 0.15, 0.15, 0.15, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]

                Spinner:
                    id: satellite_spinner
                    text: 'Выберите спутник'
                    values: app.satellites_names_with_add
                    size_hint_y: None
                    size: 280, 50
                    background_color: 0.12, 0.12, 0.12, 1
                    color: 1, 1, 1, 1

                BaseButton:
                    pos_hint: {'center_x': 0.5}
                    text: 'Задать параметры спутника'
                    size_hint_y: None
                    size: 280, 50
                    on_release:
                        app.root.transition.direction = 'up'
                        app.root.current = 'tempsat'

                Label:
                    text: 'Координаты спутника:'
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size
                    size_hint_y: None
                    height: 30
                    color: 1, 1, 1, 1
                    bold: True

                TextInput:
                    id: sat_cords_input
                    hint_text: 'x; y; z'
                    multiline: False
                    size_hint_y: None
                    size: 280, 50
                    background_color: 0.1, 0.1, 0.1, 1
                    foreground_color: 1, 1, 1, 1
                    padding: [10, 10, 10, 10]
                    font_size: 16
        BoxLayout:
            padding: [5, 0, 5, 0]
            spacing: 15
            orientation: 'horizontal'
            size_hint_y: None
            height: 50



            BaseButton:
                text: 'Рассчитать для антенны-передатчика'
                size_hint: None, None
                size: 280, 50
                pos_hint: {'center_x': 0.5}
                on_release: root.calculate('from_antenna')

            TextInput:
                id: other_params_input
                hint_text: 'l2; l3; l4; l5; R; T'
                multiline: False
                size_hint_y: None
                size_hint_x: 1
                height: 50
                background_color: 0.1, 0.1, 0.1, 1
                foreground_color: 1, 1, 1, 1
                font_size: 16

            BaseButton:
                text: 'Рассчитать для спутника-передатчика'
                size_hint: None, None
                size: 280, 50
                pos_hint: {'center_x': 0.5}
                on_release: root.calculate('from_satellite')



        BackButton:
            text: 'Назад в меню'
            size_hint: None, None
            size: 150, 40
            pos_hint: {'center_x': 0.5}
            on_release:
                app.root.transition.direction = 'right'
                app.root.current = 'menu'


<BaseTempConstructorScreen>:
    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 20

        Label:
            id: title_label
            text: root.title_text
            font_size: '28sp'
            size_hint_y: None
            height: 50
            halign: 'center'
            valign: 'middle'
            text_size: self.size
            bold: True
            color: 1, 1, 1, 1

        GridLayout:
            cols: 2
            spacing: 15
            size_hint_y: None
            height: self.minimum_height

            Label:
                text: 'Мощность передатчика (Вт):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: output_transmitter
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Потери в передатчике (дБ):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: loss_transmitter
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Диаметр антенны (м):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: antenna_diameter
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Фокусное расстояние (м):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: focus_antenna
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'КПД антенны (от 0 до 1):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: antenna_efficiency
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Рабочая частота (Гц):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: frequency
                multiline: False
                input_filter: 'int'
                size_hint_y: None
                height: 40

        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 20
            padding: [100, 0]

            BaseButton:
                text: 'Сохранить'
                on_release: root.save_params()

            BackButton:
                text: 'Назад'
                on_release:
                    app.root.transition.direction = 'down'
                    app.root.current = 'optimize'

<OptimizeScreen>:
    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos

    GridLayout:
        cols: 2
        padding: 20
        spacing: 10

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.45
            spacing: 20
            padding: [30, 50, 30, 30] 

            BoxLayout:
                orientation: 'vertical'
                padding: 15
                spacing: 15
                size_hint_y: None
                height: self.minimum_height
                canvas.before:
                    Color:
                        rgba: 0.15, 0.15, 0.15, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [15]

                Spinner:
                    id: satellite_spinner
                    text: 'Выберите спутник'
                    size_hint: None, None
                    size: 280, 50
                    background_color: 0.12, 0.12, 0.12, 1
                    color: 1, 1, 1, 1
                    pos_hint: {'center_x': 0.5}
                    values: app.satellites_names_with_add

                BaseButton:
                    pos_hint: {'center_x': 0.5}
                    text: 'Задать параметры спутника'
                    size_hint: None, None
                    size: 280, 50
                    on_release: 
                        app.root.transition.direction = 'up'
                        app.root.current = 'tempopt'

                Label:
                    text: 'Координаты спутника:'
                    size_hint_y: None
                    height: 30
                    color: 1, 1, 1, 1
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size
                    bold: True

                BoxLayout:
                    size_hint_y: None
                    height: 50
                    padding: [20, 0]
                    TextInput:
                        id: sat_cords_input
                        hint_text: 'x; y; z'
                        multiline: False
                        size_hint: 1, None
                        height: 50
                        background_color: 0.1, 0.1, 0.1, 1
                        foreground_color: 1, 1, 1, 1
                        padding: [10, 10, 10, 10]
                        font_size: 16

                Label:
                    text: 'Координаты антенны:'
                    size_hint_y: None
                    height: 30
                    color: 1, 1, 1, 1
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size
                    bold: True

                BoxLayout:
                    size_hint_y: None
                    height: 50
                    padding: [20, 0]
                    TextInput:
                        id: ant_cords_input
                        hint_text: 'широта; долгота; высота над у. м.'
                        multiline: False
                        size_hint: 1, None
                        height: 50
                        background_color: 0.1, 0.1, 0.1, 1
                        foreground_color: 1, 1, 1, 1
                        padding: [10, 10, 10, 10]
                        font_size: 16

                Label:
                    text: 'Прочие параметры:'
                    size_hint_y: None
                    height: 30
                    color: 1, 1, 1, 1
                    halign: 'center'
                    valign: 'middle'
                    text_size: self.size
                    bold: True

                BoxLayout:
                    size_hint_y: None
                    height: 50
                    padding: [20, 0]
                    TextInput:
                        id: other_params_input
                        hint_text: 'l2; l3; l4; l5; R; T'
                        multiline: False
                        size_hint: 1, None
                        height: 50
                        background_color: 0.1, 0.1, 0.1, 1
                        foreground_color: 1, 1, 1, 1
                        padding: [10, 10, 10, 10]
                        font_size: 16

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.4
            padding: 15
            spacing: 10
            canvas.before:
                Color:
                    rgba: 0.15, 0.15, 0.15, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [15]

            Label:
                text: 'Подходящие антенны'
                font_size: '20sp'
                size_hint_y: None
                height: 40
                halign: 'center'
                valign: 'middle'
                text_size: self.size
                bold: True
                color: 1, 1, 1, 1

            ScrollView:
                do_scroll_x: False

                GridLayout:
                    id: antenna_list
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 10
                    padding: 10

                    Label:
                        id: result_label
                        text: ''
                        color: 1, 1, 1, 1
                        font_size: 16
                        halign: 'left'
                        valign: 'top'
                        text_size: self.width, None
                        size_hint_y: None
                        height: self.texture_size[1]
        BoxLayout:
            orientation: 'horizontal'
            spacing: 15
            size_hint: None, None
            height: 50
            BaseButton:
                text: 'Подобрать антенны'
                size_hint: None, None
                size: 200, 50
                on_release:
                    root.optimize()

            BackButton:
                text: 'Назад в меню'
                size_hint: None, None
                size: 150, 50
                on_release:
                    app.root.transition.direction = 'right'
                    app.root.current = 'menu'

        BoxLayout:
            size_hint: None, None
            height: 50

<BaseConstructorScreen>:
    canvas.before:
        Color:
            rgba: 0.07, 0.07, 0.07, 1
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        orientation: 'vertical'
        padding: 30
        spacing: 20

        Label:
            id: title_label
            text: root.title_text
            font_size: '28sp'
            size_hint_y: None
            height: 50
            halign: 'center'
            valign: 'middle'
            text_size: self.size
            bold: True
            color: 1, 1, 1, 1

        Spinner:
            id: spinner
            text: root.choose_text
            on_text: root.fill_inputs()
            size_hint: None, None
            size: 250, 50
            pos_hint: {'center_x' : 0.5}
            values: root.obj_names

        GridLayout:
            cols: 2
            spacing: 15
            size_hint_y: None
            height: self.minimum_height

            Label:
                text: 'Название'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: name
                multiline: False
                size_hint_y: None
                height: 40

            Label:
                text: 'Мощность передатчика (Вт):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: output_transmitter
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Потери в передатчике (дБ):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: loss_transmitter
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Диаметр антенны (м):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: antenna_diameter
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Фокусное расстояние (м):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: focus_antenna
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'КПД антенны (от 0 до 1):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: antenna_efficiency
                multiline: False
                input_filter: 'float'
                size_hint_y: None
                height: 40

            Label:
                text: 'Рабочая частота (Гц):'
                halign: 'right'
                valign: 'middle'
                text_size: self.size
                color: 1, 1, 1, 1
            TextInput:
                id: frequency
                multiline: False
                input_filter: 'int'
                size_hint_y: None
                height: 40

        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 20
            padding: [100, 0]

            BaseButton:
                text: 'Сохранить'
                on_release: root.save_params()

            BackButton:
                text: 'Назад'
                on_release:
                    app.root.transition.direction = 'right'
                    app.root.current = 'menu'
